# -*- coding: utf-8 -*-
"""
Taxonomia canônica de subtemas por área (foco residência USP).
Usada por reclassify_subtemas.py para agrupar os ~2000 subtemas fragmentados
em categorias consistentes por área.

As chaves DEVEM bater exatamente com o campo `area` do banco.

REVISÃO v2 (ago/2026): taxonomia expandida após auditoria que revelou
~40-50% de erro de classificação na v1. Adicionadas categorias faltantes
e desmembradas categorias-balde.
"""

CANONICAL = {
    "Medicina Preventiva e Social": [
        "Princípios e Diretrizes do SUS",
        "Atenção Primária à Saúde",
        "Estratégia Saúde da Família e Equipe Multiprofissional",
        "Legislação e Financiamento do SUS",
        "Controle Social e Participação Popular",
        "Redes de Atenção à Saúde",
        "Modelos de Atenção e Reforma Sanitária",
        "Determinantes Sociais da Saúde e Vulnerabilidade",
        "Sistemas de Informação em Saúde",
        "Vigilância em Saúde e Notificação Compulsória",
        "Vigilância Sanitária e Ambiental",
        "Indicadores de Saúde e Mortalidade",
        "Transição Demográfica e Epidemiológica",
        "Estudos Epidemiológicos (Classificação e Desenho)",
        "Estudos Epidemiológicos (Análise Estatística e Aplicação)",
        "Estudos Observacionais (Coorte, Caso-Controle, Transversal, Ecológico)",
        "Estatística de Testes Diagnósticos",
        "Medicina Baseada em Evidências e Revisão Sistemática",
        "Bioestatística e Testes de Hipótese",
        "Níveis de Prevenção e Prevenção Quaternária",
        "Rastreamento Populacional",
        "Saúde Ocupacional e do Trabalhador",
        "Ética Médica e Bioética",
        "Comunicação Médico-Paciente e Humanização",
        "Ferramentas da APS (SOAP, PTS, Genograma, Método Centrado na Pessoa)",
        "Imunização e Programas de Saúde",
        "Epidemiologia das Doenças Transmissíveis",
        "Saúde Mental na Atenção Primária",
        "Saúde Indígena e Populações Específicas",
    ],
    "Pediatria": [
        "Crescimento e Desenvolvimento Neuropsicomotor",
        "Crescimento e Desenvolvimento",
        "Aleitamento Materno e Alimentação Complementar",
        "Imunização (PNI) e Calendário Vacinal",
        "Triagem Neonatal e Cuidados com o Recém-Nascido",
        "Sala de Parto e Reanimação Neonatal",
        "Período Neonatal: Doenças Respiratórias",
        "Período Neonatal: Doenças Infecciosas e Sífilis/STORCH",
        "Período Neonatal: Doenças Hematológicas e Icterícia",
        "Período Neonatal: Doenças Neurológicas e Sensoriais",
        "Período Neonatal: Doenças do Metabolismo",
        "Infecções Congênitas (STORCH e Sífilis)",
        "Sepse Neonatal",
        "Diarreia Aguda, Reidratação e Parasitoses",
        "Distúrbios Hidroeletrolíticos e Fluidoterapia",
        "Infecções Respiratórias Agudas (Pneumonia, Bronquiolite, Crupe)",
        "Asma na Infância",
        "Doenças Exantemáticas e Infectocontagiosas",
        "Kawasaki e Vasculites (Henoch-Schönlein)",
        "Anemias e Doença Falciforme na Infância",
        "Desnutrição, Obesidade e Avaliação Nutricional Infantil",
        "Cardiopatias Congênitas",
        "Infecção do Trato Urinário e Refluxo Vesicoureteral",
        "Glomerulopatias na Infância (Nefrótica, Nefrítica, SHU)",
        "Convulsão Febril e Emergências Neurológicas",
        "Parada Cardiorrespiratória Pediátrica (PALS)",
        "Cetoacidose Diabética e Diabetes na Infância",
        "Maus-tratos e Violência contra a Criança",
        "Adolescência e Puberdade",
        "Febre Reumática",
        "Febre Reumática e Doenças Pós-infecciosas",
        "Neoplasias na Infância e Neutropenia Febril",
        "Dermatologia Pediátrica",
        "Hematologia Pediátrica (Coagulopatias e PTI)",
        "Ortopedia e Reumatologia Pediátrica",
        "Oftalmologia e Otorrinolaringologia Pediátrica",
        "Emergências e Intoxicações Pediátricas",
        "Imunodeficiências Primárias",
        "Doenças Gastrointestinais Crônicas (Doença Celíaca, APLV, DII)",
        "Fibrose Cística e Doenças Respiratórias Crônicas",
    ],
    "Ginecologia e Obstetrícia": [
        "Ciclo Menstrual e Fisiologia Hormonal",
        "Anticoncepção e Planejamento Familiar",
        "Amenorreia e Síndrome dos Ovários Policísticos",
        "Sangramento Uterino Anormal e Miomatose",
        "Endometriose e Dor Pélvica Crônica",
        "Vulvovaginites e Cervicites",
        "Doença Inflamatória Pélvica e IST",
        "Infertilidade Conjugal",
        "Climatério e Terapia Hormonal",
        "Rastreamento e Câncer de Colo Uterino",
        "Mastologia e Câncer de Mama",
        "Câncer de Endométrio e Ovário",
        "Incontinência Urinária e Prolapsos",
        "Assistência Pré-natal",
        "Mecanismo e Assistência ao Parto",
        "Síndromes Hipertensivas da Gestação",
        "Diabetes Gestacional e Diabetes na Gestação",
        "Diabetes Gestacional",
        "Infecções na Gestação (HIV, Sífilis, STORCH)",
        "Sangramento da Primeira Metade da Gestação (Aborto, Ectópica, Mola)",
        "Sangramento da Segunda Metade da Gestação (DPP, Placenta Prévia)",
        "Trabalho de Parto Prematuro e Rotura de Membranas",
        "Vitalidade Fetal e Restrição de Crescimento",
        "Puerpério e Hemorragia Pós-parto",
        "Infecção Puerperal",
        "Gestação de Alto Risco e Intercorrências Clínicas",
        "Aborto Legal e Violência Sexual",
    ],
    "Cirurgia": [
        "Avaliação Pré-operatória e Risco Cirúrgico",
        "Anestesiologia e Técnica Operatória",
        "Resposta Metabólica ao Trauma e Pós-operatório",
        "Infecção de Sítio Cirúrgico e Cicatrização",
        "Atendimento Inicial ao Trauma (ATLS)",
        "Trauma Torácico",
        "Trauma Abdominal",
        "Trauma Cranioencefálico e Raquimedular",
        "Trauma Cervical e Vascular",
        "Trauma Pélvico e Urológico",
        "Choque e Transfusão no Trauma",
        "Queimaduras",
        "Apendicite Aguda",
        "Colecistite e Colelitíase",
        "Coledocolitíase e Colangite",
        "Pancreatite Aguda",
        "Diverticulite Aguda",
        "Abdome Agudo Obstrutivo",
        "Abdome Agudo Perfurativo",
        "Isquemia Mesentérica",
        "Hérnias da Parede Abdominal",
        "Doenças Orificiais (Hemorroida, Fissura, Fístula)",
        "Câncer Colorretal",
        "Doenças do Esôfago (DRGE, Acalasia, Câncer)",
        "Estômago (Úlcera, HDA, Câncer Gástrico)",
        "Cirurgia Bariátrica e Complicações",
        "Cirurgia Vascular Periférica (Isquemia Arterial, Varizes, TVP)",
        "Aneurismas e Dissecção de Aorta",
        "Cirurgia Torácica e Mediastino",
        "Tireoide e Paratireoide",
        "Cirurgia Pediátrica",
        "Tumores de Pele e Partes Moles (Melanoma, CBC, CEC)",
        "Tumores de Pele e Partes Moles",
        "Urologia (Litíase, HPB, Neoplasia Renal, Escroto Agudo)",
        "Ortopedia e Fraturas",
        "Oftalmologia Cirúrgica",
        "Otorrinolaringologia Cirúrgica",
        "Neurocirurgia (Hemorragia, Hidrocefalia, Tumor)",
    ],
    "Clínica Médica": [
        "Hipertensão Arterial Sistêmica",
        "Dislipidemia e Risco Cardiovascular",
        "Síndromes Coronarianas Agudas (IAM e Angina)",
        "Insuficiência Cardíaca",
        "Arritmias e Fibrilação Atrial",
        "Valvopatias",
        "Pericardiopatias",
        "Diabetes Mellitus e Complicações",
        "Tireoidopatias",
        "Distúrbios da Adrenal e Hipófise",
        "Asma",
        "DPOC",
        "Tromboembolismo Venoso e TEP",
        "Pneumonia e Infecções Respiratórias",
        "Tuberculose",
        "Derrame Pleural e Doenças Pleurais",
        "Doenças Pulmonares Intersticiais e Outras Pneumopatias",
        "Doenças Pulmonares Intersticiais",
        "Injúria Renal Aguda",
        "Doença Renal Crônica",
        "Distúrbios Hidroeletrolíticos e Ácido-Base",
        "Glomerulopatias e Síndrome Nefrótica/Nefrítica",
        "Litíase Urinária e Infecção Urinária",
        "Doenças do Esôfago e Estômago (DRGE, Úlcera, Dispepsia)",
        "Doença Inflamatória Intestinal e Diarreia Crônica",
        "Hepatites Virais",
        "Cirrose e Complicações",
        "Doenças das Vias Biliares e Pâncreas",
        "Anemias",
        "Leucemias, Linfomas e Mieloma",
        "Distúrbios da Coagulação e Plaquetas",
        "Artrites e Doenças Reumatológicas (AR, Gota, Osteoartrite)",
        "Lúpus e Doenças Autoimunes Sistêmicas (Esclerose, Vasculites)",
        "AVC e Doenças Cerebrovasculares",
        "Cefaleias",
        "Epilepsia e Doenças Neuromusculares",
        "Demências e Parkinson",
        "HIV/AIDS e Infecções Oportunistas",
        "Infecções de Pele e ISTs (Sífilis, Hanseníase, Micoses)",
        "Sepse e Choque",
        "Endocardite Infecciosa",
        "Arboviroses e Doenças Infecciosas Tropicais",
        "Emergências Clínicas e Intoxicações",
        "Parada Cardiorrespiratória e Suporte Avançado de Vida",
        "Transtornos Psiquiátricos (Depressão, Ansiedade, Psicoses)",
        "Dependência Química e Tabagismo",
        "Dermatologia (Lesões Cutâneas, Eczemas, Psoríase)",
        "Geriatria e Cuidados Paliativos",
        "Oncologia (Rastreio e Neoplasias Sólidas)",
        "Otorrinolaringologia",
        "Oftalmologia Clínica",
        "Osteoporose e Doença Óssea Metabólica",
        "Ventilação Mecânica e Medicina Intensiva",
    ],
}
