# -*- coding: utf-8 -*-
"""
Taxonomia canônica de subtemas por área (foco residência USP).
Usada por reclassify_subtemas.py para agrupar os ~2000 subtemas fragmentados
em ~25-30 assuntos consistentes por área.

As chaves DEVEM bater exatamente com o campo `area` do banco.
"""

CANONICAL = {
    "Medicina Preventiva e Social": [
        "Princípios e Diretrizes do SUS",
        "Atenção Primária à Saúde",
        "Legislação e Financiamento do SUS",
        "Controle Social e Participação Popular",
        "Redes de Atenção à Saúde",
        "Modelos de Atenção e Reforma Sanitária",
        "Sistemas de Informação em Saúde",
        "Vigilância em Saúde e Notificação Compulsória",
        "Vigilância Sanitária",
        "Indicadores de Saúde",
        "Transição Demográfica e Epidemiológica",
        "Estudos Observacionais (Coorte, Caso-Controle, Transversal, Ecológico)",
        "Ensaios Clínicos e Randomização",
        "Medidas de Associação e Impacto (RR, OR, NNT)",
        "Testes Diagnósticos (Sensibilidade, VPP, ROC)",
        "Medicina Baseada em Evidências",
        "Bioestatística e Testes de Hipótese",
        "Níveis de Prevenção e Prevenção Quaternária",
        "Rastreamento Populacional",
        "Saúde Ocupacional e do Trabalhador",
        "Ética Médica e Bioética",
        "Ferramentas da APS (SOAP, PTS, Método Centrado na Pessoa)",
        "Imunização e Programas de Saúde",
        "Epidemiologia das Doenças Transmissíveis",
    ],
    "Pediatria": [
        "Crescimento e Desenvolvimento",
        "Aleitamento Materno e Alimentação",
        "Imunização (PNI)",
        "Triagem Neonatal e Cuidados com o Recém-Nascido",
        "Reanimação Neonatal",
        "Distúrbios Respiratórios do Recém-Nascido",
        "Icterícia Neonatal",
        "Infecções Congênitas (STORCH e Sífilis)",
        "Sepse Neonatal",
        "Diarreia Aguda e Reidratação",
        "Distúrbios Hidroeletrolíticos e Fluidoterapia",
        "Infecções Respiratórias Agudas (Pneumonia, Bronquiolite, Crupe)",
        "Asma na Infância",
        "Doenças Exantemáticas",
        "Kawasaki e Vasculites (Henoch-Schönlein)",
        "Parasitoses e Verminoses",
        "Anemias na Infância",
        "Desnutrição e Obesidade Infantil",
        "Cardiopatias Congênitas",
        "Infecção do Trato Urinário e Refluxo",
        "Glomerulopatias na Infância (Nefrótica, Nefrítica, SHU)",
        "Convulsão Febril e Emergências Neurológicas",
        "Parada Cardiorrespiratória Pediátrica (PALS)",
        "Cetoacidose Diabética na Infância",
        "Maus-tratos e Violência",
        "Adolescência e Puberdade",
        "Febre Reumática e Doenças Pós-infecciosas",
        "Neoplasias na Infância",
        "Dermatologia Pediátrica",
    ],
    "Ginecologia e Obstetrícia": [
        "Ciclo Menstrual e Fisiologia Hormonal",
        "Anticoncepção e Planejamento Familiar",
        "Amenorreia e Síndrome dos Ovários Policísticos",
        "Sangramento Uterino Anormal e Miomatose",
        "Endometriose",
        "Vulvovaginites e Cervicites",
        "Doença Inflamatória Pélvica e IST",
        "Climatério e Terapia Hormonal",
        "Rastreamento e Câncer de Colo Uterino",
        "Mastologia e Câncer de Mama",
        "Câncer de Endométrio e Ovário",
        "Incontinência Urinária e Prolapsos",
        "Assistência Pré-natal",
        "Mecanismo e Assistência ao Parto",
        "Síndromes Hipertensivas da Gestação",
        "Diabetes Gestacional",
        "Infecções na Gestação (HIV, Sífilis, STORCH)",
        "Abortamento e Doença Trofoblástica",
        "Gestação Ectópica",
        "Hemorragias da 2ª Metade (DPP, Placenta Prévia)",
        "Trabalho de Parto Prematuro e Rotura de Membranas",
        "Vitalidade Fetal e Restrição de Crescimento",
        "Puerpério e Hemorragia Pós-parto",
        "Infecção Puerperal",
        "Gestação de Alto Risco",
        "Aborto Legal e Violência Sexual",
    ],
    "Cirurgia": [
        "Avaliação Pré-operatória e Risco Cirúrgico",
        "Resposta Metabólica ao Trauma e Pós-operatório",
        "Infecção de Sítio Cirúrgico e Cicatrização",
        "Atendimento Inicial ao Trauma (ATLS)",
        "Trauma Torácico",
        "Trauma Abdominal",
        "Trauma Cranioencefálico e Raquimedular",
        "Trauma Cervical e Vascular",
        "Trauma Pélvico",
        "Choque e Transfusão no Trauma",
        "Queimaduras",
        "Apendicite Aguda",
        "Colecistite e Colelitíase",
        "Coledocolitíase e Colangite",
        "Pancreatite Aguda",
        "Diverticulite Aguda",
        "Abdome Agudo Obstrutivo",
        "Abdome Agudo Perfurativo",
        "Isquemia Mesentérica",
        "Hérnias da Parede Abdominal",
        "Doenças Orificiais (Hemorroida, Fissura, Fístula)",
        "Câncer Colorretal",
        "Doenças do Esôfago (DRGE, Acalasia, Câncer)",
        "Estômago (Úlcera, HDA, Câncer Gástrico)",
        "Cirurgia Bariátrica",
        "Cirurgia Vascular (Aneurisma, Isquemia Arterial, Varizes)",
        "Tireoide e Paratireoide",
        "Cirurgia Pediátrica",
        "Tumores de Pele e Partes Moles",
    ],
    "Clínica Médica": [
        "Hipertensão Arterial Sistêmica",
        "Dislipidemia e Risco Cardiovascular",
        "Síndromes Coronarianas Agudas",
        "Insuficiência Cardíaca",
        "Arritmias e Fibrilação Atrial",
        "Valvopatias",
        "Diabetes Mellitus e Complicações Agudas",
        "Tireoidopatias",
        "Distúrbios da Adrenal e Hipófise",
        "Asma e DPOC",
        "Tromboembolismo Venoso e TEP",
        "Pneumonia e Infecções Respiratórias",
        "Tuberculose",
        "Derrame Pleural e Doenças Pleurais",
        "Doenças Pulmonares Intersticiais",
        "Injúria Renal Aguda",
        "Doença Renal Crônica",
        "Distúrbios Hidroeletrolíticos e Ácido-Base",
        "Glomerulopatias",
        "Doenças do Esôfago e Estômago",
        "Doença Inflamatória Intestinal e Diarreia Crônica",
        "Hepatites Virais",
        "Cirrose e Complicações",
        "Anemias",
        "Leucemias e Linfomas",
        "Distúrbios da Coagulação e Plaquetas",
        "Artrites e Doenças Reumatológicas (AR, Gota, Osteoartrite)",
        "Lúpus e Doenças Autoimunes Sistêmicas",
        "AVC e Doenças Cerebrovasculares",
        "Cefaleias",
        "Epilepsia e Doenças Neuromusculares",
        "Demências e Parkinson",
        "HIV/AIDS e Infecções Oportunistas",
        "Sepse e Choque",
        "Endocardite Infecciosa",
        "Arboviroses e Doenças Infecciosas Tropicais",
        "Emergências Clínicas e Intoxicações",
        "Transtornos Psiquiátricos",
    ],
}
