# -*- coding: utf-8 -*-
"""
Finaliza a reclassificação SEM usar API: mapeia manualmente (por rótulo) os
subtemas não-canônicos que sobraram para a taxonomia canônica.
Seguro/reversível: subtema_orig já guarda o original. Só faz UPDATE.
"""
import sqlite3, os
from canonical_subtemas import CANONICAL

DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "medquest.db")

MAPPING = {
 "Medicina Preventiva e Social": {
  "Estudos Ecológicos": "Estudos Observacionais (Coorte, Caso-Controle, Transversal, Ecológico)",
  "Estudos de Coorte": "Estudos Observacionais (Coorte, Caso-Controle, Transversal, Ecológico)",
  "Delineamento de Estudo": "Estudos Observacionais (Coorte, Caso-Controle, Transversal, Ecológico)",
  "Comunicação de Más Notícias": "Ferramentas da APS (SOAP, PTS, Método Centrado na Pessoa)",
  "Comunicação Médico-Paciente": "Ferramentas da APS (SOAP, PTS, Método Centrado na Pessoa)",
  "Humanização em Medicina": "Ferramentas da APS (SOAP, PTS, Método Centrado na Pessoa)",
  "Trabalho em Equipe Interprofissional": "Ferramentas da APS (SOAP, PTS, Método Centrado na Pessoa)",
  "Acolhimento e Classificação de Risco": "Ferramentas da APS (SOAP, PTS, Método Centrado na Pessoa)",
  "Intervalo de Confiança": "Bioestatística e Testes de Hipótese",
  "Teste T": "Bioestatística e Testes de Hipótese",
  "Testes Estatísticos": "Bioestatística e Testes de Hipótese",
  "Aborto Legal": "Ética Médica e Bioética",
  "Autonomia e Sigilo Médico": "Ética Médica e Bioética",
  "Cuidados Paliativos Domiciliares": "Ética Médica e Bioética",
  "Anos Potenciais de Vida Perdidos": "Indicadores de Saúde",
  "Mortalidade Ajustada": "Indicadores de Saúde",
  "Mortalidade Específica": "Indicadores de Saúde",
  "Prevalência": "Indicadores de Saúde",
  "Benefícios Previdenciários": "Saúde Ocupacional e do Trabalhador",
  "Doença Ocupacional": "Saúde Ocupacional e do Trabalhador",
  "Cascata de Cuidado HIV/Sífilis": "Epidemiologia das Doenças Transmissíveis",
  "Número Básico de Reprodução R0": "Epidemiologia das Doenças Transmissíveis",
  "Determinantes Sociais da Saúde": "Modelos de Atenção e Reforma Sanitária",
  "História da Saúde no Brasil": "Modelos de Atenção e Reforma Sanitária",
  "Vulnerabilidade e Determinantes Sociais": "Modelos de Atenção e Reforma Sanitária",
  "Eficácia e Efetividade Vacinal": "Imunização e Programas de Saúde",
  "Política Nacional de Atenção Integral à Saúde da Mulher": "Imunização e Programas de Saúde",
  "Notificação de Receita Controlada": "Vigilância Sanitária",
  "Saneamento Básico e Prevenção de Doenças": "Vigilância Sanitária",
  "Níveis de Prevenção": "Níveis de Prevenção e Prevenção Quaternária",
  "Promoção da Saúde e Prevenção Primordial": "Níveis de Prevenção e Prevenção Quaternária",
  "Princípios do SUS e Acesso Universal": "Princípios e Diretrizes do SUS",
  "Redução de Danos": "Atenção Primária à Saúde",
  "Saúde Mental na Atenção Primária": "Atenção Primária à Saúde",
  "Território e Adscrição na APS": "Atenção Primária à Saúde",
  "Território e Vulnerabilidade Social": "Atenção Primária à Saúde",
  "Violência e Diversidade Sexual": "Atenção Primária à Saúde",
  "Validade de Estudos Epidemiológicos": "Medicina Baseada em Evidências",
  "Vieses em Rastreamento": "Rastreamento Populacional",
 },
 "Pediatria": {
  "Púrpura Trombocitopênica Imune": "Hematologia Pediátrica",
  "Distúrbio de Coagulação": "Hematologia Pediátrica",
  "Hemofilia - Trauma Craniano": "Hematologia Pediátrica",
  "Crise de Sequestro Esplênico": "Anemias na Infância",
  "Síndrome Torácica Aguda": "Anemias na Infância",
  "Desenvolvimento Neuropsicomotor": "Crescimento e Desenvolvimento",
  "Transtorno do Espectro Autista": "Crescimento e Desenvolvimento",
  "Transtorno Específico de Aprendizagem": "Crescimento e Desenvolvimento",
  "Dor do Crescimento": "Ortopedia e Reumatologia Pediátrica",
  "Artrite Idiopática Juvenil": "Ortopedia e Reumatologia Pediátrica",
  "Artrite Séptica Neonatal": "Ortopedia e Reumatologia Pediátrica",
  "Artrite Séptica de Quadril": "Ortopedia e Reumatologia Pediátrica",
  "Pé Plano Flexível": "Ortopedia e Reumatologia Pediátrica",
  "Estrabismo do Lactente": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Glaucoma Congênito": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Obstrução Congênita do Ducto Nasolacrimal": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Triagem de Acuidade Visual": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Otite Externa": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Mastoidite Aguda": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Mastoidite - Complicação": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Cefaleia Secundária a Sinusite": "Oftalmologia e Otorrinolaringologia Pediátrica",
  "Avaliação Nutricional Infantil": "Desnutrição e Obesidade Infantil",
  "Diagnóstico Nutricional": "Desnutrição e Obesidade Infantil",
  "Leucemia Linfoide Aguda": "Neoplasias na Infância",
  "Neutropenia Febril": "Neoplasias na Infância",
  "Síndrome de Lise Tumoral": "Neoplasias na Infância",
  "Imunodeficiência Combinada Grave - Vacinação": "Imunodeficiências",
  "Imunodeficiência Humoral": "Imunodeficiências",
  "Imunodeficiência Primária - Investigação": "Imunodeficiências",
  "Ingestão de Corpo Estranho": "Emergências e Intoxicações Pediátricas",
  "Intoxicação por Benzodiazepínicos": "Emergências e Intoxicações Pediátricas",
  "Intoxicação por Bloqueador de Canal de Cálcio": "Emergências e Intoxicações Pediátricas",
  "Trauma Pediátrico - Pneumotórax Hipertensivo": "Emergências e Intoxicações Pediátricas",
  "Traumatismo Cranioencefálico em Menores de 2 Anos": "Emergências e Intoxicações Pediátricas",
  "Doença do Refluxo Gastroesofágico": "Diarreia Aguda e Reidratação",
  "Síndrome do Intestino Curto": "Diarreia Aguda e Reidratação",
  "Erro Inato do Metabolismo": "Triagem Neonatal e Cuidados com o Recém-Nascido",
  "Fenilcetonúria": "Triagem Neonatal e Cuidados com o Recém-Nascido",
  "Icterícia Colestática do Lactente": "Icterícia Neonatal",
  "Síndrome Alcoólica Fetal": "Infecções Congênitas (STORCH e Sífilis)",
  "Transmissão Vertical do HIV": "Infecções Congênitas (STORCH e Sífilis)",
  "Toxoplasmose Congênita": "Infecções Congênitas (STORCH e Sífilis)",
  "Dengue com Sinais de Alarme": "Doenças Exantemáticas",
  "Mononucleose - Exantema por Amoxicilina": "Doenças Exantemáticas",
  "Impetigo Bolhoso": "Dermatologia Pediátrica",
  "Molusco Contagioso": "Dermatologia Pediátrica",
  "Síndrome da Pele Escaldada Estafilococíaca": "Dermatologia Pediátrica",
  "Dermatite Atópica": "Dermatologia Pediátrica",
  "Síndrome Hemolítico-Urêmica": "Glomerulopatias na Infância (Nefrótica, Nefrítica, SHU)",
  "Síndrome Nefrótica": "Glomerulopatias na Infância (Nefrótica, Nefrítica, SHU)",
  "Febre sem Sinais Localizatórios": "Infecções Respiratórias Agudas (Pneumonia, Bronquiolite, Crupe)",
  "Evento Adverso Pós-vacinação": "Imunização (PNI)",
  "Telarca Precoce": "Adolescência e Puberdade",
  "Uso de Substâncias no Adolescente": "Adolescência e Puberdade",
  "Cuidados Paliativos Pediátricos": "Emergências e Intoxicações Pediátricas",
 },
 "Ginecologia e Obstetrícia": {
  "Dismenorreia": "Ciclo Menstrual e Fisiologia Hormonal",
  "Distúrbio Menstrual": "Ciclo Menstrual e Fisiologia Hormonal",
  "Anatomia Pélvica Feminina": "Ciclo Menstrual e Fisiologia Hormonal",
  "Aborto Legal": "Aborto Legal e Violência Sexual",
  "Violência Sexual": "Aborto Legal e Violência Sexual",
  "Aconselhamento Pré-concepcional": "Assistência Pré-natal",
  "Exames Laboratoriais Pré-natal": "Assistência Pré-natal",
  "Diagnóstico de Gestação": "Assistência Pré-natal",
  "Anemia na Gestação": "Assistência Pré-natal",
  "Lombalgia na Gestação": "Assistência Pré-natal",
  "Hiperêmese Gravídica": "Assistência Pré-natal",
  "Depressão na Gestação": "Assistência Pré-natal",
  "Falência Ovariana Prematura": "Climatério e Terapia Hormonal",
  "Fisiologia Placentária": "Assistência Pré-natal",
  "Miomatose Uterina": "Sangramento Uterino Anormal e Miomatose",
  "Miomatose Uterina (Submucoso)": "Sangramento Uterino Anormal e Miomatose",
  "Ultrassonografia no Primeiro Trimestre": "Assistência Pré-natal",
  "Abdome Agudo Ginecológico": "Endometriose",
  "Abdome Agudo na Gestação": "Gestação de Alto Risco",
  "Adenomiose": "Sangramento Uterino Anormal e Miomatose",
  "Analgesia de Parto": "Mecanismo e Assistência ao Parto",
  "Anestesia Obstétrica": "Mecanismo e Assistência ao Parto",
  "Indução do Trabalho de Parto": "Mecanismo e Assistência ao Parto",
  "Desproporção Cefalopélvica": "Mecanismo e Assistência ao Parto",
  "Parto Operatório": "Mecanismo e Assistência ao Parto",
  "Partograma": "Mecanismo e Assistência ao Parto",
  "Classificação de Robson": "Mecanismo e Assistência ao Parto",
  "Atipia Glandular Citológica": "Rastreamento e Câncer de Colo Uterino",
  "Colposcopia e NIC na Gestação": "Rastreamento e Câncer de Colo Uterino",
  "Câncer de Colo Uterino - Estadiamento": "Rastreamento e Câncer de Colo Uterino",
  "Lesão Intraepitelial de Baixo Grau": "Rastreamento e Câncer de Colo Uterino",
  "Neoplasia Intraepitelial Cervical": "Rastreamento e Câncer de Colo Uterino",
  "Seguimento Pós-tratamento de NIC": "Rastreamento e Câncer de Colo Uterino",
  "Cisto Mamário": "Mastologia e Câncer de Mama",
  "Classificação BI-RADS em Mamografia": "Mastologia e Câncer de Mama",
  "Conduta no BI-RADS 3": "Mastologia e Câncer de Mama",
  "Câncer de Mama Localmente Avançado": "Mastologia e Câncer de Mama",
  "Mastite Periareolar/Ectasia Ductal": "Mastologia e Câncer de Mama",
  "Câncer de Vulva": "Câncer de Endométrio e Ovário",
  "Hiperplasia Endometrial Atípica": "Câncer de Endométrio e Ovário",
  "Avaliação da Vitalidade Fetal": "Vitalidade Fetal e Restrição de Crescimento",
  "Cardiotocografia Intraparto": "Vitalidade Fetal e Restrição de Crescimento",
  "Sofrimento Fetal Intraparto": "Vitalidade Fetal e Restrição de Crescimento",
  "Malformações Fetais": "Vitalidade Fetal e Restrição de Crescimento",
  "Procedimentos Invasivos Fetais": "Vitalidade Fetal e Restrição de Crescimento",
  "Doença Hemolítica Perinatal": "Gestação de Alto Risco",
  "Cardiopatia na Gestação": "Gestação de Alto Risco",
  "Hiperandrogenismo": "Amenorreia e Síndrome dos Ovários Policísticos",
  "Hirsutismo": "Amenorreia e Síndrome dos Ovários Policísticos",
  "Síndrome dos Ovários Policísticos": "Amenorreia e Síndrome dos Ovários Policísticos",
  "Endometriose e Infertilidade": "Endometriose",
  "Dor Pélvica Crônica Neuropática": "Endometriose",
  "Incontinência Urinária de Esforço": "Incontinência Urinária e Prolapsos",
  "Incontinência Urinária de Urgência": "Incontinência Urinária e Prolapsos",
  "Infertilidade - Fator Masculino": "Anticoncepção e Planejamento Familiar",
  "Infertilidade por Fator Tuboperitoneal": "Anticoncepção e Planejamento Familiar",
  "Laqueadura Tubária": "Anticoncepção e Planejamento Familiar",
  "Planejamento Familiar": "Anticoncepção e Planejamento Familiar",
  "Planejamento Familiar - Categorias OMS": "Anticoncepção e Planejamento Familiar",
  "Método Ogino-Knaus": "Anticoncepção e Planejamento Familiar",
  "Disfunção Sexual e Resposta Sexual": "Anticoncepção e Planejamento Familiar",
  "Saúde do Homem Trans/Contracepção": "Anticoncepção e Planejamento Familiar",
  "Malformações Müllerianas": "Amenorreia e Síndrome dos Ovários Policísticos",
  "Prevenção de Pré-eclâmpsia": "Síndromes Hipertensivas da Gestação",
  "Profilaxia de Pré-eclâmpsia": "Síndromes Hipertensivas da Gestação",
  "Síndrome HELLP": "Síndromes Hipertensivas da Gestação",
  "Sífilis Primária": "Doença Inflamatória Pélvica e IST",
 },
 "Cirurgia": {
  "Doença de Hirschsprung": "Cirurgia Pediátrica",
  "Atresia de Vias Biliares": "Cirurgia Pediátrica",
  "Estenose Hipertrófica do Piloro": "Cirurgia Pediátrica",
  "Manejo de Vias Aéreas no Trauma": "Atendimento Inicial ao Trauma (ATLS)",
  "Via Aérea Difícil no Trauma": "Atendimento Inicial ao Trauma (ATLS)",
  "Avaliação Inicial do Politraumatizado": "Atendimento Inicial ao Trauma (ATLS)",
  "Materiais e Técnicas de Sutura": "Infecção de Sítio Cirúrgico e Cicatrização",
  "Cicatrização de Feridas": "Infecção de Sítio Cirúrgico e Cicatrização",
  "Drenos Cirúrgicos": "Resposta Metabólica ao Trauma e Pós-operatório",
  "Seroma Pós-Operatório": "Resposta Metabólica ao Trauma e Pós-operatório",
  "Peritonite Pós-Operatória": "Resposta Metabólica ao Trauma e Pós-operatório",
  "Classificações na Cirurgia Geral": "Avaliação Pré-operatória e Risco Cirúrgico",
  "Abscesso Anorretal": "Doenças Orificiais (Hemorroida, Fissura, Fístula)",
  "Doença Hemorroidária": "Doenças Orificiais (Hemorroida, Fissura, Fístula)",
  "Doença Pilonidal": "Doenças Orificiais (Hemorroida, Fissura, Fístula)",
  "Adenocarcinoma Gástrico": "Estômago (Úlcera, HDA, Câncer Gástrico)",
  "Tumor Estromal Gastrointestinal (GIST)": "Estômago (Úlcera, HDA, Câncer Gástrico)",
  "Anatomia do Mediastino": "Trauma Torácico",
  "Cirrose e Transplante Hepático": "Câncer Colorretal",
  "Lesão Inalatória": "Queimaduras",
  "Trauma Vascular de Membro": "Trauma Cervical e Vascular",
  "Câncer de Próstata": "Urologia",
  "Hiperplasia Prostática Benigna": "Urologia",
  "Litíase Urinária - Conduta Conservadora": "Urologia",
  "Manejo da Nefrolitíase": "Urologia",
  "Pterígio": "Oftalmologia",
  "Retinopatia Diabética": "Oftalmologia",
  "Retinopatia Diabética/Hipertensiva": "Oftalmologia",
 },
 "Clínica Médica": {
  "Gota": "Artrites e Doenças Reumatológicas (AR, Gota, Osteoartrite)",
  "Artrite Reumatoide": "Artrites e Doenças Reumatológicas (AR, Gota, Osteoartrite)",
  "Espondilite Anquilosante": "Artrites e Doenças Reumatológicas (AR, Gota, Osteoartrite)",
  "Psoríase e Artrite Psoriásica": "Artrites e Doenças Reumatológicas (AR, Gota, Osteoartrite)",
  "Esclerose Sistêmica": "Lúpus e Doenças Autoimunes Sistêmicas",
  "Síndrome Antifosfolípide": "Lúpus e Doenças Autoimunes Sistêmicas",
  "Síndrome do Anticorpo Antifosfolipídeo": "Lúpus e Doenças Autoimunes Sistêmicas",
  "Síndrome do Anticorpo Antifosfolipídeo (SAAF)": "Lúpus e Doenças Autoimunes Sistêmicas",
  "Lesão Renal Aguda no Lúpus Eritematoso Sistêmico": "Lúpus e Doenças Autoimunes Sistêmicas",
  "Peritonite Bacteriana Espontânea": "Cirrose e Complicações",
  "Síndrome Hepatorrenal": "Cirrose e Complicações",
  "Encefalopatia Hipertensiva": "Hipertensão Arterial Sistêmica",
  "Hemorragia Digestiva Varicosa": "Cirrose e Complicações",
  "Hemorragia Digestiva por Varizes Esofágicas": "Cirrose e Complicações",
  "Escore MELD": "Cirrose e Complicações",
  "Lesão Renal Aguda na Cirrose": "Cirrose e Complicações",
  "Hemocromatose Hereditária": "Cirrose e Complicações",
  "Hiperplasia Nodular Focal": "Cirrose e Complicações",
  "Cuidados Paliativos": "Geriatria e Cuidados Paliativos",
  "Manejo da Dispneia em Cuidados Paliativos": "Geriatria e Cuidados Paliativos",
  "Proporcionalidade Terapêutica em Demência Avançada": "Geriatria e Cuidados Paliativos",
  "Luto Complicado": "Geriatria e Cuidados Paliativos",
  "Abordagem da Queda e Polifarmácia no Idoso": "Geriatria e Cuidados Paliativos",
  "Critérios de Beers": "Geriatria e Cuidados Paliativos",
  "Farmacologia no Idoso": "Geriatria e Cuidados Paliativos",
  "Delirium no Idoso": "Geriatria e Cuidados Paliativos",
  "Demência no Idoso": "Demências e Parkinson",
  "Síndrome da Fragilidade no Idoso": "Geriatria e Cuidados Paliativos",
  "Prevenção de Quedas e Osteoporose": "Geriatria e Cuidados Paliativos",
  "Câncer de Pulmão - Estadiamento": "Oncologia e Neoplasias",
  "Câncer de Pulmão - Localização Anatômica": "Oncologia e Neoplasias",
  "Câncer Colorretal": "Oncologia e Neoplasias",
  "Rastreamento de Câncer Colorretal": "Oncologia e Neoplasias",
  "Neoplasia de Pâncreas": "Oncologia e Neoplasias",
  "Síndrome de Lynch": "Oncologia e Neoplasias",
  "Síndrome da Veia Cava Superior": "Oncologia e Neoplasias",
  "Síndrome de Veia Cava Superior": "Oncologia e Neoplasias",
  "Síndrome de Lise Tumoral": "Oncologia e Neoplasias",
  "Esporotricose": "Dermatologia",
  "Cisto Epidérmico": "Dermatologia",
  "Dermatite Atópica": "Dermatologia",
  "Dermatite de Contato": "Dermatologia",
  "Dermatite de Contato Alérgica": "Dermatologia",
  "Farmacodermia": "Dermatologia",
  "Larva Migrans Cutânea": "Dermatologia",
  "Erisipela e Celulite": "Dermatologia",
  "Lesões por Pressão": "Dermatologia",
  "Doença de Ménière": "Otorrinolaringologia",
  "Síndrome Vestibular Aguda Central": "Otorrinolaringologia",
  "Osteoporose": "Osteoporose e Doença Óssea",
  "Diagnóstico de Osteoporose": "Osteoporose e Doença Óssea",
  "Densitometria Óssea": "Osteoporose e Doença Óssea",
  "Vitamina D e Osteoporose": "Osteoporose e Doença Óssea",
  "Transtorno Bipolar - Episódio Maníaco": "Transtornos Psiquiátricos",
  "Transtorno Bipolar - Depressão": "Transtornos Psiquiátricos",
  "Antidepressivos - ISRS": "Transtornos Psiquiátricos",
  "Transtornos de Ansiedade - Fatores de Risco": "Transtornos Psiquiátricos",
  "Transtornos de Personalidade - Classificação": "Transtornos Psiquiátricos",
  "Síndrome de Abstinência Alcoólica": "Transtornos Psiquiátricos",
  "Abstinência Alcoólica": "Transtornos Psiquiátricos",
  "Delirium Tremens": "Transtornos Psiquiátricos",
  "Intoxicação Alcoólica": "Emergências Clínicas e Intoxicações",
  "Dependência de Benzodiazepínicos": "Transtornos Psiquiátricos",
  "Dependência de Nicotina": "Transtornos Psiquiátricos",
  "Dependência de Tabaco": "Transtornos Psiquiátricos",
  "Parkinsonismo Farmacológico": "Demências e Parkinson",
  "Choque Anafilático": "Emergências Clínicas e Intoxicações",
  "Parada Cardiorrespiratória": "Emergências Clínicas e Intoxicações",
  "Intoxicação por Antidepressivos Tricíclicos": "Emergências Clínicas e Intoxicações",
  "Intoxicação por Opioides": "Emergências Clínicas e Intoxicações",
  "Intoxicação por Organofosforados e Carbamatos": "Emergências Clínicas e Intoxicações",
  "Intoxicações Exógenas": "Emergências Clínicas e Intoxicações",
  "Edema Agudo de Pulmão": "Insuficiência Cardíaca",
  "Derrame Pleural na Insuficiência Cardíaca": "Insuficiência Cardíaca",
  "Hiponatremia na Insuficiência Cardíaca": "Distúrbios Hidroeletrolíticos e Ácido-Base",
  "Hipercalemia Grave e Eletrocardiograma": "Distúrbios Hidroeletrolíticos e Ácido-Base",
  "Acidose Respiratória na Síndrome de Guillain-Barré": "Epilepsia e Doenças Neuromusculares",
  "Síndrome de Guillain-Barré": "Epilepsia e Doenças Neuromusculares",
  "Cardiomiopatia Hipertrófica Obstrutiva": "Insuficiência Cardíaca",
  "Estenose Aórtica": "Valvopatias",
  "Sinais Semiológicos da Insuficiência Aórtica": "Valvopatias",
  "Pericardite Aguda": "Valvopatias",
  "Tamponamento Cardíaco": "Emergências Clínicas e Intoxicações",
  "Dissecção Aórtica": "Emergências Clínicas e Intoxicações",
  "Bloqueios de Condução - ECG": "Arritmias e Fibrilação Atrial",
  "Taquicardia Supraventricular de QRS Estreito": "Arritmias e Fibrilação Atrial",
  "Infarto Agudo do Miocárdio com Supra de ST": "Síndromes Coronarianas Agudas",
  "Infarto com Bloqueio de Ramo Esquerdo": "Síndromes Coronarianas Agudas",
  "Conduta na Síndrome Coronariana Aguda": "Síndromes Coronarianas Agudas",
  "Prevenção Cardiovascular com Estatinas": "Dislipidemia e Risco Cardiovascular",
  "Anemia Ferropriva": "Anemias",
  "Anemia Ferropriva no Idoso": "Anemias",
  "Anemia Ferropriva por Sangramento Intestinal": "Anemias",
  "Anemia Hemolítica Autoimune": "Anemias",
  "Púrpura Trombocitopênica Trombótica": "Distúrbios da Coagulação e Plaquetas",
  "Reações Transfusionais (TACO)": "Distúrbios da Coagulação e Plaquetas",
  "Reversão da Anticoagulação por Varfarina": "Distúrbios da Coagulação e Plaquetas",
  "Duração da Anticoagulação no TEP Pós-Operatório": "Tromboembolismo Venoso e TEP",
  "Manejo do Tromboembolismo Pulmonar": "Tromboembolismo Venoso e TEP",
  "Trombólise no Tromboembolismo Pulmonar Grave": "Tromboembolismo Venoso e TEP",
  "Diabetes - Tratamento": "Diabetes Mellitus e Complicações Agudas",
  "Tratamento do Diabetes Mellitus Tipo 2": "Diabetes Mellitus e Complicações Agudas",
  "Tratamento da Cetoacidose Diabética": "Diabetes Mellitus e Complicações Agudas",
  "Diagnóstico de Cetoacidose Diabética": "Diabetes Mellitus e Complicações Agudas",
  "Complicações do Pré-Diabetes": "Diabetes Mellitus e Complicações Agudas",
  "Prevenção do Diabetes Mellitus Tipo 2": "Diabetes Mellitus e Complicações Agudas",
  "Gastroparesia Diabética": "Diabetes Mellitus e Complicações Agudas",
  "Avaliação do Pé Diabético": "Diabetes Mellitus e Complicações Agudas",
  "Crise Adrenal": "Distúrbios da Adrenal e Hipófise",
  "Insuficiência Adrenal Secundária": "Distúrbios da Adrenal e Hipófise",
  "Hiperaldosteronismo Primário": "Distúrbios da Adrenal e Hipófise",
  "Hiperprolactinemia": "Distúrbios da Adrenal e Hipófise",
  "Disfunção Erétil": "Distúrbios da Adrenal e Hipófise",
  "Tratamento da Obesidade": "Diabetes Mellitus e Complicações Agudas",
  "Exacerbação Aguda da DPOC": "Asma e DPOC",
  "Tratamento Farmacológico da DPOC": "Asma e DPOC",
  "Tratamento da Doença Pulmonar Obstrutiva Crônica": "Asma e DPOC",
  "Bronquiectasia": "Asma e DPOC",
  "Fibrose Pulmonar Idiopática": "Doenças Pulmonares Intersticiais",
  "Correlação Tomográfica em Doenças Pulmonares": "Doenças Pulmonares Intersticiais",
  "Gravidade da Pneumonia Adquirida na Comunidade": "Pneumonia e Infecções Respiratórias",
  "Manejo da Pneumonia Adquirida na Comunidade": "Pneumonia e Infecções Respiratórias",
  "Pneumonia Adquirida na Comunidade Grave": "Pneumonia e Infecções Respiratórias",
  "Tratamento da Pneumonia Adquirida na Comunidade": "Pneumonia e Infecções Respiratórias",
  "Pneumonia Aspirativa": "Pneumonia e Infecções Respiratórias",
  "Pneumonia Associada à Ventilação Mecânica": "Pneumonia e Infecções Respiratórias",
  "Tosse Crônica/DRGE": "Doenças do Esôfago e Estômago",
  "Doença do Refluxo Gastroesofágico (DRGE)": "Doenças do Esôfago e Estômago",
  "Úlcera Péptica": "Doenças do Esôfago e Estômago",
  "Úlcera Péptica/H. pylori": "Doenças do Esôfago e Estômago",
  "Classificação de Forrest": "Doenças do Esôfago e Estômago",
  "Hemostasia Endoscópica na Úlcera Péptica": "Doenças do Esôfago e Estômago",
  "Profilaxia de Úlcera de Estresse": "Doenças do Esôfago e Estômago",
  "Lesão de Dieulafoy": "Doenças do Esôfago e Estômago",
  "Síndrome de Mallory-Weiss": "Doenças do Esôfago e Estômago",
  "Doença Inflamatória Intestinal": "Doença Inflamatória Intestinal e Diarreia Crônica",
  "Doença de Crohn": "Doença Inflamatória Intestinal e Diarreia Crônica",
  "Manejo da Diarreia Aguda": "Doença Inflamatória Intestinal e Diarreia Crônica",
  "Tratamento Sintomático da Diarreia Aguda": "Doença Inflamatória Intestinal e Diarreia Crônica",
  "Infecção por Clostridioides difficile": "Doença Inflamatória Intestinal e Diarreia Crônica",
  "Pancreatite Aguda": "Doenças do Esôfago e Estômago",
  "Diagnóstico de Pancreatite Aguda": "Doenças do Esôfago e Estômago",
  "Diagnóstico por Imagem na Pancreatite Aguda": "Doenças do Esôfago e Estômago",
  "Marcadores Laboratoriais na Pancreatite Aguda": "Doenças do Esôfago e Estômago",
  "Suporte Nutricional na Pancreatite Aguda": "Doenças do Esôfago e Estômago",
  "Pancreatite Crônica": "Doenças do Esôfago e Estômago",
  "Meningite Tuberculosa": "Tuberculose",
  "Infecção Latente por Tuberculose": "Tuberculose",
  "Tuberculose Pulmonar e Ganglionar": "Tuberculose",
  "Pneumocistose em HIV": "HIV/AIDS e Infecções Oportunistas",
  "Síndrome de Reconstituição Imune no HIV": "HIV/AIDS e Infecções Oportunistas",
  "Sífilis e PEP HIV": "HIV/AIDS e Infecções Oportunistas",
  "Profilaxia de Endocardite Infecciosa": "Endocardite Infecciosa",
  "Sepse e Critérios de Gravidade": "Sepse e Choque",
  "Tratamento de Pielonefrite por ESBL": "Pneumonia e Infecções Respiratórias",
  "Hemorragia Subaracnoidea": "AVC e Doenças Cerebrovasculares",
  "Tratamento do Acidente Vascular Cerebral Isquêmico Minor": "AVC e Doenças Cerebrovasculares",
  "Trombólise no Acidente Vascular Cerebral Isquêmico": "AVC e Doenças Cerebrovasculares",
  "Tratamento Crise de Enxaqueca": "Cefaleias",
  "Efeitos Colaterais de Fármacos": "Emergências Clínicas e Intoxicações",
  "Efeitos Hemodinâmicos da Ventilação Mecânica": "Emergências Clínicas e Intoxicações",
  "Síndrome do Desconforto Respiratório Agudo": "Emergências Clínicas e Intoxicações",
  "Trepopneia": "Insuficiência Cardíaca",
  "Lesão Renal Aguda": "Injúria Renal Aguda",
}}


def main():
    conn = sqlite3.connect(DB)
    cur = conn.cursor()
    # validação: todo destino precisa ser canônico da sua área
    problems = []
    for area, m in MAPPING.items():
        canon = set(CANONICAL[area])
        for src, dst in m.items():
            if dst not in canon:
                problems.append(f"{area}: destino inválido '{dst}' (de '{src}')")
    if problems:
        print("ABORTADO — destinos inválidos:")
        print("\n".join(problems))
        return

    total = 0
    for area, m in MAPPING.items():
        for src, dst in m.items():
            cur.execute("UPDATE questions SET subtema=? WHERE area=? AND subtema=?", (dst, area, src))
            total += cur.rowcount
    conn.commit()
    print(f"Reclassificação manual aplicada: {total} questões atualizadas.")

    print("\nSubtemas distintos por área agora:")
    for area, in cur.execute("SELECT DISTINCT area FROM questions WHERE area!='' ORDER BY area"):
        n = cur.execute("SELECT COUNT(DISTINCT subtema) FROM questions WHERE area=? AND subtema!=''", (area,)).fetchone()[0]
        canon = set(CANONICAL.get(area, []))
        rest = cur.execute(f"SELECT COUNT(*) FROM questions WHERE area=? AND missing_alts=0 AND subtema!='' AND subtema NOT IN ({','.join('?'*len(canon))})", (area, *canon)).fetchone()[0]
        print(f"  {area}: {n} subtemas | ainda não-canônicos: {rest}")
    conn.close()


if __name__ == "__main__":
    main()
