import sqlite3

db = sqlite3.connect("C:/dev/MedQuest/app/backend/medquest.db")
db.row_factory = sqlite3.Row

# The query string generated by AI
fts_query = '"falta de ar" OR "dispneia" OR "dificuldade respiratoria" OR "apneia" OR "insuficiencia respiratoria" OR "hipoxia"'

rows = db.execute("""
    SELECT q.id, snippet(questions_fts, 0, '<mark>', '</mark>', '...', 20) as snippet
    FROM questions_fts fts
    JOIN questions q ON q.id = fts.rowid
    WHERE questions_fts MATCH ?
    ORDER BY rank
    LIMIT 3
""", (fts_query,)).fetchall()

for r in rows:
    print(r["id"], r["snippet"])
